- name: Install flannel network plugin
  shell: 'curl -sSL "https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true"
  | sed "s/amd64/{{ item }}/g" | kubectl create -f -'
  with_items: "{{ flannel_arch }}"
