- name: Check if flannel is already installed
  shell: "kubectl get daemonset kube-flannel-ds --namespace=kube-system"
  register: result
  ignore_errors: yes
  changed_when: no

- name: Copy flannel descriptor
  copy:
    src: "files/k8s_flannel_{{ kubeadm_flannel_arch }}.yml"
    dest: "./k8s_flannel_{{ kubeadm_flannel_arch }}.yml"
  when: result.rc != 0

- name: Install flannel network plugin
  shell: 'kubectl create -f k8s_flannel_{{ kubeadm_flannel_arch }}.yml'
  when: result.rc != 0
