- name: Copy flannel descriptors
  copy:
    src: "files/k8s_flannel_{{ item }}.yml"
    dest: "./k8s_flannel_{{ item }}.yml"
  with_items: "{{ kubeadm_flannel_archs }}"

- name: Check if flannel is already installed
  shell: "kubectl get daemonset kube-flannel-ds-{{ item }} --namespace=kube-system"
  register: result
  ignore_errors: yes
  with_items: "{{ kubeadm_flannel_archs }}"
  changed_when: no

- name: Install flannel network plugin
  shell: 'kubectl create -f k8s_flannel_{{ item.item }}.yml'
  with_items: "{{ result.results }}"
  when: item.rc != 0
