---
# tasks file for kubeadm

- name: Include distribution specifc vars
  include_vars: '{{ ansible_distribution }}.yml'

- name: Ubuntu 16 install
  include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'

- name: Retieve access token
  include: get_token.yml
  delegate_to: "{{ groups['k8s-master'][0] }}"

- set_fact:
    kubeadm_master_ip: "{{ hostvars[groups['k8s-master'][0]]['ansible_host'] }}"
  when: kubeadm_master_ip is not defined

- name: Master setup
  include: "master.yml"
  when: "'k8s-master' in group_names"

- name: Worker setup
  include: "worker.yml"
  when: "'k8s-workers' in group_names"
